import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');

test('index.html exposes markdown insertion buttons migrated from article-studio', () => {
    const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');

    assert.match(html, /id="markdown-toolbox-group"/);
    assert.match(html, /id="image-preview-pane"/);
    assert.match(html, /id="image-preview-image"/);
    assert.match(html, /id="btn-markdown-metadata"/);
    assert.match(html, /id="markdown-meta-drawer"/);
    assert.match(html, /id="quick-create-modal"/);
    assert.match(html, /id="markdown-visual-canvas"/);
    assert.match(html, /id="markdown-visual-inspector"/);
    assert.match(html, /data-md-insert="bold"/);
    assert.match(html, /data-md-insert="h2"/);
    assert.match(html, /data-md-insert="list"/);
    assert.match(html, /data-md-insert="quote"/);
    assert.match(html, /data-md-insert="math-inline"/);
    assert.match(html, /data-md-insert="math-block"/);
    assert.match(html, /data-md-insert="ref"/);
    assert.match(html, /data-md-insert="cs-embed"/);
    assert.match(html, /data-md-insert="anim"/);
    assert.match(html, /data-md-insert="fx-embed"/);
    assert.match(html, /data-md-insert="callout-note"/);
    assert.match(html, /data-md-insert="animts-block"/);
    assert.match(html, /data-md-insert="color-inline"/);
    assert.match(html, /data-md-insert="color-change-inline"/);
    assert.match(html, /data-md-insert="quiz-tf"/);
    assert.match(html, /data-md-insert="quiz-choice"/);
    assert.match(html, /data-md-insert="quiz-multi"/);
});

test('main.js wires markdown insert actions and Ctrl+V image paste flow', () => {
    const source = fs.readFileSync(path.join(root, 'src/main.js'), 'utf8');

    assert.match(source, /markdownInsertButtons/);
    assert.match(source, /function applyMarkdownInsertAction/);
    assert.match(source, /function openQuickCreateModal/);
    assert.match(source, /function setMarkdownMetaDrawerOpen/);
    assert.match(source, /function renderMarkdownVisualEditor/);
    assert.match(source, /function insertPastedShaderImages/);
    assert.match(source, /function wrapMarkdownSelection/);
    assert.match(source, /function insertMarkdownBlockSnippet/);
    assert.match(source, /function collectClipboardImageFiles/);
    assert.match(source, /function insertPastedMarkdownImages/);
    assert.match(source, /function createWorkspaceImageFileFromPaste/);
    assert.match(source, /function createWorkspaceImageFileForShaderPaste/);
    assert.match(source, /function imagePreviewSrcFromActiveFile/);
    assert.match(source, /function resolveViewerPagePath/);
    assert.match(source, /articleStudioViewerPreview\.v1/);
    assert.match(source, /params\.set\('studio_preview', '1'\)/);
    assert.match(source, /article-studio-preview-update/);
    assert.match(source, /addEventListener\('paste'/);
    assert.match(source, /已粘贴图片/);
    assert.match(source, /readMarkdownSelectionText\('动画说明'\)/);
    assert.match(source, /readMarkdownSelectionText\('Shader 说明'\)/);
    assert.match(source, /anims:anims\/你的动画文件\.anim\.ts/);
    assert.match(source, /fx:\.\/shaders\/demo\.fx/);
    assert.match(source, /if \(key === 'math-inline'\)/);
    assert.match(source, /if \(key === 'math-block'\)/);
    assert.match(source, /wrapMarkdownSelection\('\$', '\$', '公式'\)/);
    assert.match(source, /insertMarkdownBlockSnippet\('\$\$\\n公式\\n\$\$\\n', '公式'\)/);
    assert.match(source, /> \[!NOTE\]/);
    assert.match(source, /joinRepoPathParts\(markdownDir,\s*'imgs'\)/);
    assert.match(source, /isBinaryFileMode\(mode\)[\s\S]*extractBase64ContentFromDataUrl[\s\S]*docs\.extraEntries\.push/);
    assert.match(source, /extractBase64ContentFromDataUrl[\s\S]*encoding:\s*'base64'/);
    assert.match(source, /detectFileMode\(pathValue\)[\s\S]*'image'/);
    assert.match(source, /detectFileMode\(pathValue\)[\s\S]*'shaderfx'/);
    assert.match(source, /function renderMarkdownVisualBlockPreview/);
    assert.match(source, /markdown-visual-block-render/);
    assert.match(source, /renderMarkdownVisualEmbedPreview/);
    assert.doesNotMatch(source, /insertMarkdownBlockSnippet\(`\{\{anim:/);
    assert.doesNotMatch(source, /globalThis\.open\(`\/site\/pages\/viewer\.html\?file=/);
});
